### ISSUE TITLE
Option to change resolution.

### ISSUE THREAD

**Issue by sweebee** [georg90/pimatic-android-hybrid-app#1]
I have android tablet on the wall and i'm using pimatic as webapp now. But the problem is that the buttons are quite small. I nice feature in this mobile-frontend container would be to change the default resolution (the resolution that the mobile-frontend reads). So if this app sends a lower resolution, the buttons will be bigger (like zooming).

**Comment by georg90** [comment]
You can implement a switcher on the Settings page, which actually just sets some variables (see: http://android.okhelp.cz/display-screen-dimension/) and if this is empty it uses auto resolution.

**Comment by georg90** [comment]
added to my todo list: https://github.com/georg90/pimatic-android-hybrid-app/commit/2075d7ef9c62ba663ca32b2fba2b04ad649b7832

**Comment by georg90** [comment]
@sweebee can you try this: https://github.com/georg90/pimatic-android-hybrid-app/blob/master/pimatic.apk
